Fix Trustchain failing from command line
Tribler/kotlin-ipv8 pull request #57
Opened 2021-11-22 15:20 UTC by KoningR

A (quite naive) solution to fix #56 . At the moment, I am unsure if this is *the best* way of fixing this, but I am hoping the project maintainer can comment.

2022-01-18 10:48 UTC, KoningR commented
Would anyone please be so kind as to consider reviewing and merging this PR or stating what should be changed about it? The functionality in this PR is critical for my project (at least, to me it currently appears that way) and I would like to work from the master branch if that is possible.

2022-01-18 11:08 UTC, InvictusRMC commented
@KoningR I will merge this today, can you fix the conflicts first?

2022-01-18 11:21 UTC, InvictusRMC requested changes
We're changing the used Dispatcher for the demo application now. Probably not something we want to be doing. Please look into it.

2022-01-18 11:21 UTC, InvictusRMC commented on ipv8/src/main/java/nl/tudelft/ipv8/Community.kt
> +        scope = CoroutineScope(dispatcher + job)
(4/4) This will now be `Dispatchers.Default` as opposed to being `Dispatchers.Main` in the demo application.

2022-01-18 11:21 UTC, InvictusRMC commented on demo-jvm/src/main/java/nl/tudelft/ipv8/jvm/demo/Application.kt
> +        ipv8.start(dispatcher)
(1/4) Now we're passing `Dispatchers.Default`.

2022-01-18 11:21 UTC, InvictusRMC commented on ipv8/src/main/java/nl/tudelft/ipv8/IPv8.kt
> +    fun start(dispatcher: CoroutineDispatcher = Dispatchers.Main) {
(2/4) Resulting in this not being `Dispatchers.Main`

2022-01-18 11:21 UTC, InvictusRMC commented on ipv8/src/main/java/nl/tudelft/ipv8/IPv8.kt
> +            overlay.load(dispatcher)
(3/4) We're now passing `Dispatchers.Default`.

2022-01-18 13:25 UTC, InvictusRMC commented
The rewrites in the `load` functions clash with overrides in the `superapp` project. So I cannot merge this yet. Either rewrite those 
 overrides or allow for a second definition of the `load` function if that is possible in Kotlin.

2022-01-18 15:13 UTC, InvictusRMC commented on ipv8/src/main/java/nl/tudelft/ipv8/Overlay.kt
> +     * Called to inintialize this overlay.
```suggestion
     * Called to initialize this overlay.
```

2022-01-18 15:43 UTC, InvictusRMC commented
@KoningR your changes appear to break al EVA tests.

2022-03-29 14:01 UTC, KoningR commented
I am now using ipv8 directly instead of trustchain (for unrelated reasons). Thus, this problem is not relevant to my project anymore, nor am I involved with the super app for the time being. Time constraints disallow me to spend further time on this. I am leaving the issue and branch open but am closing this PR.

2022-03-29 14:01 UTC, closed without merging