Eva improvements
Tribler/kotlin-ipv8 pull request #71
Opened 2023-02-28 11:57 UTC by KoningR

This PR introduces 3 improvements to EVA:

- Every EVA instance now has an optional argument ```encrypt = true``` to enable encryption of all EVA packets.
- The (de)serialization of EVA acknowledgement packets has been improved to convert integers directly to bytes instead of converting them to string literals. This saves space and time (+- 97% faster serialization, 95% faster deserialization).
- Periodic checking of scheduled transfers is now ```@Synchronized``` to prevent random race conditions that become prevalent in low-latency scenarios (e.g. when checking for new transfers every <10 ms).

2023-03-02 15:18 UTC, InvictusRMC approved these changes

2023-03-07 10:40 UTC, rmadhwal commented
I took a look at the changes and I'm curious if this change could cause issues if two incompatible evaProtocols try to communicate with each other. i.e. one has encryption enabled and one doesn't ?

Maybe the network packet should indicate that the contents are encrypted so in the decryption step regardless of if the evaProtocol uses encryption on its messages, an encrypted message can be decrypted ?

2023-03-13 13:02 UTC, InvictusRMC requested changes
Please fix the new merging issues and address @rmadhwal comments 😄

2023-04-04 11:59 UTC, InvictusRMC approved these changes

2023-04-04 11:59 UTC, merged